enforce System.Text.Json version 8.0.4
eclipse-tractusx/policy-hub pull request #184
Opened 2024-07-26 11:14 UTC by ntruchsess

## Description

package dependency to System.Text.Json set to version 8.0.4

## Why

System.Text.Json 8.0.0 has a vulnerability-issue that must be fixed.

## Issue

https://github.com/eclipse-tractusx/portal/issues/369

## Checklist

Please delete options that are not relevant.

- [X] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/policy-hub/blob/main/docs/technical-documentation/dev-process/How%20to%20contribute.md)
- [X] I have performed a self-review of my own code
- [X] I have successfully tested my changes locally
- [X] I have checked that new and existing tests pass locally with my changes

2024-07-26 11:21 UTC, evegufy approved these changes

2024-07-29 06:31 UTC, Phil91 requested changes
We should wait until PR https://github.com/eclipse-tractusx/portal-backend/pull/875 is merged and the framework nuget packages are updated. We than can directly update the nuget packages for this project as well.

2024-07-29 14:12 UTC, ntruchsess commented
> We should wait until PR [eclipse-tractusx/portal-backend#875](https://github.com/eclipse-tractusx/portal-backend/pull/875) is merged and the framework nuget packages are updated. We than can directly update the nuget packages for this project as well.

done

2024-07-29 14:14 UTC, Phil91 approved these changes

2024-07-29 14:23 UTC, merged