docs: add documentation to add policies and attributes
eclipse-tractusx/policy-hub pull request #214
Opened 2024-10-07 10:56 UTC by Phil91

## Description

* adjust documentation structure to align with TRG1
* add documentation to add policies and policy attributes

## Why

To align with trg 1 and give the overview of how to add new policies and policy attributes.

## Issue

Refs: #178 #197

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/policy-hub/blob/main/docs/technical-documentation/dev-process/How%20to%20contribute.md)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added copyright and license headers, footers (for .md files) or files (for images)

2024-10-24 05:02 UTC, evegufy requested changes
please add /docs/README.md and align with https://github.com/eclipse-tractusx/ssi-authority-schema-registry/pull/71 where it makes sense

2024-10-24 07:15 UTC, Phil91 commented
> [eclipse-tractusx/ssi-authority-schema-registry#71](https://github.com/eclipse-tractusx/ssi-authority-schema-registry/pull/71)

@evegufy did add the readme

2024-11-06 07:21 UTC, Phil91 commented on docs/architecture/Index.md
> +- [06. Runtime View (To be added.)](./Index.md)
adjusted

2024-11-06 07:21 UTC, Phil91 commented on docs/architecture/Index.md
> +This documentation follows the arc42 template to provide a comprehensive overview of the SSI Authority & Schema Registry App.
adjusted

2024-11-06 07:27 UTC, Phil91 commented on docs/architecture/Index.md
> +- [06. Runtime View (To be added.)](./Index.md)
created a pr for the fix in asr: https://github.com/eclipse-tractusx/ssi-authority-schema-registry/pull/87

2024-11-06 21:25 UTC, evegufy requested changes

2024-11-06 21:25 UTC, evegufy commented on docs/known-knowns/known-issues-and-limitations.md
can be removed due to https://github.com/eclipse-tractusx/policy-hub/issues/186#issuecomment-2293670726
for future reference, I'd put it under docs/admin

2024-11-06 21:25 UTC, evegufy commented on docs/admin/add-data-process/index.md
might make sense to rename docs/admin/add-policies/add-policies.md

2024-11-07 12:58 UTC, Phil91 commented on docs/known-knowns/known-issues-and-limitations.md
adjusted

2024-11-19 05:46 UTC, evegufy approved these changes

2024-11-19 05:47 UTC, merged