chore: adjust policy hub docu
eclipse-tractusx/policy-hub pull request #56
Opened 2024-02-27 08:39 UTC by Phil91

## Description

Adjust documentation of the policy hub

## Why

To give the user a good overview of the policy hub

## Issue

N/A

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/policy-hub/blob/main/docs/technical-documentation/dev-process/How%20to%20contribute.md)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added copyright and license headers, footers (for .md files) or files (for images)

2024-02-27 08:54 UTC, evegufy requested changes

2024-02-27 08:54 UTC, evegufy commented on docs/static/whitebox-overall-system.png
I'm wondering if we really need this diagram as image, mainly because it's not editable and against [TRG 1.04](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-4). If we really need to add it as image, ideally you add it as svg to enable some edit-ability, but I think this could quite easily also be covered in Mermaid, see example [here](https://github.com/eclipse-tractusx/policy-hub/pull/42) for data flow diagram in currently created sec assessment.

2024-02-29 09:39 UTC, Phil91 commented
> as discussed, could you please still change to latest state of the diagram regarding labels and move the requests?

@evegufy done

2024-02-29 10:06 UTC, evegufy approved these changes

2024-02-29 10:44 UTC, merged