chore(documentation): add request documentation
eclipse-tractusx/policy-hub pull request #7
Opened 2023-12-15 11:19 UTC by Phil91

## Description

* add postman collection
* add documentation with example requests

## Why

To have some example requests and explanation for the requests as well as a postman collection to test the policy hub

## Issue

N/A

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/policy-hub/blob/main/docs/developer/Technical-Documentation/Dev-Process/How-to-contribute.md#commit-and-pr-guidelines)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-02-20 10:01 UTC, evegufy commented
@Phil91 could you please update the PR if needed?

2024-02-23 13:37 UTC, Phil91 commented
> @Phil91 could you please update the PR if needed?

@evegufy I did double check and rebased to the latest version

2024-02-23 14:02 UTC, evegufy requested changes

2024-02-23 14:02 UTC, evegufy commented on docs/developer/Technical-Documentation/requests/example-requests.md
> +- SPDX-FileCopyrightText: 2021-2023 Contributors to the Eclipse Foundation
could you please still update the year?

2024-02-23 14:12 UTC, Phil91 commented on docs/developer/Technical-Documentation/requests/example-requests.md
> +- SPDX-FileCopyrightText: 2021-2023 Contributors to the Eclipse Foundation
oh thanks for the hint - updated

2024-02-23 14:49 UTC, evegufy approved these changes

2024-02-24 17:43 UTC, merged